services:
  - type: web
    name: urbansight
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: OSM_USER_AGENT
        value: "UrbanSight/2.0 (https://urbansight.onrender.com)"
      - key: DEFAULT_SEARCH_RADIUS
        value: "1000"
      - key: MAX_CONCURRENT_REQUESTS
        value: "5"
      - key: DEBUG
        value: "false"
      - key: HOST
        value: "0.0.0.0"
